# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  right_wheel:
    has_velocity_limits: true
    max_velocity: 15.707963268
    has_acceleration_limits: false
    max_acceleration: 0
  left_wheel:
    has_velocity_limits: true
    max_velocity: 15.707963268
    has_acceleration_limits: false
    max_acceleration: 0

  torso_0:
    has_velocity_limits: true
    max_velocity: 2.0943950999999998
    has_acceleration_limits: false
    max_acceleration: 0
  torso_1:
    has_velocity_limits: true
    max_velocity: 2.0943950999999998
    has_acceleration_limits: false
    max_acceleration: 0
  torso_2:
    has_velocity_limits: true
    max_velocity: 2.0943950999999998
    has_acceleration_limits: false
    max_acceleration: 0
  torso_3:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  torso_4:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  torso_5:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0

  right_arm_0:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_1:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_2:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_3:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_4:
    has_velocity_limits: true
    max_velocity: 6.2831853080000002
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_5:
    has_velocity_limits: true
    max_velocity: 6.2831853080000002
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_6:
    has_velocity_limits: true
    max_velocity: 2.094395102
    has_acceleration_limits: false
    max_acceleration: 0

  left_arm_0:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_1:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_2:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_3:
    has_velocity_limits: true
    max_velocity: 3.1415926540000001
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_4:
    has_velocity_limits: true
    max_velocity: 6.2831853080000002
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_5:
    has_velocity_limits: true
    max_velocity: 6.2831853080000002
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_6:
    has_velocity_limits: true
    max_velocity: 2.094395102
    has_acceleration_limits: false
    max_acceleration: 0

  head_0:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  head_1:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0