#topics:
#  - name: "navigation"
#    topic: "/cmd_vel_nav"
#    timeout: 0.5
#    priority: 5
#  - name: "keyboard"
#    topic: "/cmd_vel_key"
#    timeout: 0.5
#    priority: 1

twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 5
      keyboard:
        topic: cmd_vel_key
        timeout: 0.5
        priority: 10
    locks:
      pause_navigation:
        topic: pause_navigation
        timeout: 0.0
        priority: 9